### ISSUE TITLE
vim-debugstring doesn't support zsh.

### ISSUE THREAD

**Issue by andrewferrier** [bergercookie/vim-debugstring#11]
Supporting `zsh` files (filetype `zsh`) would be relatively trivial; the syntax is essentially the same as `sh.vim`. I'm not sure if copying `sh.vim` to `zsh.vim` is the right approach from a maintainability perspective, but it would be great to see `vim-debugstring` supporting this filetype.

**Comment by bergercookie** [comment]
Could you pull the latest master and try it out?
AFAICT echo-ing in zsh should be exactly the same as in Bash.

**Comment by andrewferrier** [comment]
Perfect, thanks for the super-fast response. This seems to work perfectly. Nice fix!

Thanks again for your work on this plugin. I use it daily now.
