### ISSUE TITLE
vim-debugstring doesn't support typescript

### ISSUE THREAD

**Issue by andrewferrier** [bergercookie/vim-debugstring#13]
Similar to issue #11, I think it would probably be reasonable to symlink `typescript.vim` to `javascript.vim`; the former is a superset of the latter, and so the same syntax can apply (I've tested this personally).

**Comment by bergercookie** [comment]
Sure, done, check the latest master.

Also, kind of unrelated but I decided to remove the symbolic links, I don't have ea windows system but I think they wouldn't really work there.

**Comment by andrewferrier** [comment]
Great, works well! And agreed on the symlinks. Thanks!
