### ISSUE TITLE
Inserted text incorrectly adds spaces

### ISSUE THREAD

**Issue by jdsutherland** [bergercookie/vim-debugstring#14]
I've noticed in various contexts that the inserted text adds spaces. Here's an [example](https://github.com/jdsutherland/tmux.nvim/blob/d61a97c6eb4ea7869cc9e6001dbeadaae67dd3b0/lua/tmux/navigate.lua#L35):

```lua
local function has_tmux_target(border)
	print("foo: " .. foo)
	if not wrapper.is_tmux then
		p	rint("bar: " .. bar)
		return false
		p		rint("baz: " .. baz)
	end
    ...
```

I'm fairly sure the issue stems from: https://github.com/bergercookie/vim-debugstring/blob/80295fcad6663113a3487e57fbb4465a8ed2b00f/plugin/debugstring.vim#L204-L206

**Comment by jdsutherland** [comment]
I'm guessing this is a result of remaps since it's a normal command. I have 0 and ^ maps swapped. Also P is being used by https://github.com/AndrewRadev/whitespaste.vim. 

Things seem to work fine with the line removed so far. I'll continue testing.

**Comment by bergercookie** [comment]
Yes, I think i've seen it before. probably when the line I'm editing has a `<TAB>` instead of a space before..
I 'll also see to repro this when I have some time.

**Comment by jdsutherland** [comment]
I forgot that `normal!` (bang) avoids user mappings, so what I said above can't be right. I haven't had any issues since removing those lines.

**Comment by bergercookie** [comment]
Hmm, can't repro :(

I'll close this for now.
If you can pinpoint a code snippet that this occurs for you let me know and I can re-open.
